### ISSUE TITLE
install error with php artisan key:generate

### ISSUE THREAD

**Issue by greenlevel** [bpocallaghan/laravel-admin-starter#15]
Hello, 
I am trying to install the admin, but get the following warning.

vagrant@homestead:~/code/lav$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdat                                ed dependencies. Run update to update them.
Package operations: 100 installs, 0 updates, 0 removals

I don't know how to "update" that, so i continued to the next step.
php artisan key:generate

I get these errors.
PHP Warning:  require(/home/vagrant/code/lav/vendor/autoload.php): failed to open stream: No such file or directory in /home/vagrant/code/lav/artisan on line 18

Warning: require(/home/vagrant/code/lav/vendor/autoload.php): failed to open stream: No such file or directory in /home/vagrant/code/lav/artisan on line 18
PHP Fatal error:  require(): Failed opening required '/home/vagrant/code/lav/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/vagrant/code/lav/artisan on line 18

Fatal error: require(): Failed opening required '/home/vagrant/code/lav/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/vagrant/code/lav/artisan on line 18

Please advice.
Thank you

**Comment by xewl** [comment]
`composer update --lock`

**Comment by bpocallaghan** [comment]
Hi @greenlevel 
Please shout if @xewl  solution did not work.
I am back from holidays, and will setup the project from the beginning to give it a thorough test again.

Thanks @xewl for the help :)

**Comment by greenlevel** [comment]
The composer update --lock worked.

My .env didnt have a key, so i did php artisan key:generate and i could continue.

I have the site working now.
