### ISSUE TITLE
Suggestion: Change Summernote for Toast.io

### ISSUE THREAD

**Issue by jasonmccuen** [bpocallaghan/laravel-admin-starter#19]
I've used Summernote a bit now, and I am not impressed for a few reasons:

* It does not allow me to use relative links, in both html or their built-in link builder
* It looks old and dated (ok, they have themes.. but still..)
* Development is a bit stagnant, It does not look like they are going be expanding or growing it much more than how it is today.

I've had a look for a replacement and found  
[Toast.io](https://github.com/nhnent/tui.editor), and it looks as if it does all the things Summernote does, only it uses markdown instead of a html code editor. 

I think that the majority of use-cases, WYSIWYG with Markdown would be better than WYSIWYG with 
 HTML.

It looks like it would pretty much be a drop-in replacement from what I can see. I'm not sure if there are any specific features in Summernote that makes it better.

**Comment by xewl** [comment]
I'd rather see this pass as an alternative field type.
The content type this field then creates is different, and you might need to know how to exactly parse its content when outputting. (HTML vs markdown)
(HTML vs markdown)
Maybe [GrahamCampbell/Laravel-Markdown](https://github.com/GrahamCampbell/Laravel-Markdown) could do some lifting for the output of those fields itself, just lingering.

Regarding HTML, if you really want an alternative to Summernote, I'm totally down with CKEditor.

**Comment by jasonmccuen** [comment]
I'm happy with any solution that is not Summernote, as long as I can use relative links.

The deal-breaker for me with Summernote is that I cannot use relative links. These are much more important to me than markdown. I can always add in the markdown parser how I like anyways - and I'm already using [GrahamCampbell/Laravel-Markdown](https://github.com/GrahamCampbell/Laravel-Markdown) for that purpose. 

My suggestion for markdown is because

* [HTML is parsed as HTML in markdown anyways](https://daringfireball.net/projects/markdown/syntax#html) - so people who choose to write in markup still can.
* Markdown is much easier to read
* Users will still have the WYSIWYG text editor either way with [Toast](https://github.com/nhnent/tui.editor).

My normal workflow is to get content from writers and edit it at the same time I convert it into markdown (headings, tables, ol, ul etc). Currently I do this in VS Code which outputs to a HTML, so it is just a small added step for me to copy it across. No biggie. 👍
