### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by bpocallaghan** [bpocallaghan/laravel-admin-starter#20]
Hi Guys and Gals
I figured this is the fastest way to communicate to all parties interested.

Just want to ask if anyone here is interested in a slack channel?
I do not use slack frequently but totally open to the idea, I do however use skype day to day.
Figured maybe if its only 1/2 interested - skype might do for now?

Please share your thoughts.
Happy coding :)

Thanks

**Comment by jasonmccuen** [comment]
Skype is fine for me!
