### ISSUE TITLE
Upgrade to Laravel 5.6

### ISSUE THREAD

**Issue by rap2hpoutre** [bpocallaghan/laravel-admin-starter#23]
Maybe we should consider upgrading to Laravel 5.6. (I can submit a PR if you want)

**Comment by bpocallaghan** [comment]
Hi @rap2hpoutre 
Thanks for the reminder - was meaning to get to it.
Thanks for the offer, but its oky - let me upgrade it :)

**Comment by rap2hpoutre** [comment]
Thank you!

**Comment by bpocallaghan** [comment]
Hi @rap2hpoutre 
I've pushed the upgrade to the master branch.
I did not do any thorough testing - but seems to be good - please shout.
Thanks - have a lovely day
