### ISSUE TITLE
Add Admin Navigation

### ISSUE THREAD

**Issue by bpocallaghan** [bpocallaghan/laravel-admin-starter#26]
Hi @truelogicapp

Thank your trying out this package.

You've created the new menu item (admin - settings - navigation)
Then the new menu item appeared on the left and you clicked on it... - and now the error...
I am sure you know this - but any admin navigation - needs a Controller / Model / Views and defined in the routes/web.php for it to work.

Only the Website's Pages - can be managed from the admin via the page builder...

Just want to check in before going further... :)

**Comment by truelogicapp** [comment]
Hi @bpocallaghan 

Yes i created Controller in app\Http\Controllers\Admin Folder
models in \app\Models
View in resources\views\admin
and added routes in Web.php

but when i run my custom Link then i am getting following Error

"Undefined variable: selectedNavigation (View: C:\xampp\htdocs\udrive2.0\resources\views\admin\partials\info.blade.php) 

but if i remove @include('admin.partials.info') then get following Error

"Undefined variable: HTMLDescription (View: C:\xampp\htdocs\udrive2.0\resources\views\layouts\admin.blade.php) (View: C:\xampp\htdocs\udrive2.0\resources\views\l ▶"

I am not getting $selectedNavigationId in ValidateRole Middleware

I am sure missing some step. Please guide me

Thanks!

**Comment by bpocallaghan** [comment]
Hi @truelogicapp 
How does your controller look likes.
Or more specifically - how do you return the view response.
As you will notice. All the admin controller extends the `AdminController` and the functions return the view like `return $this->view('path.to.view');`
All those 'extra' variables like the selectedNavigation / htmlDescription, etc - will be passed to the view from the parent view()

Mind having a looksy there and see if we can narrow it down :)

**Comment by truelogicapp** [comment]
@bpocallaghan  my Request not accessible in ValidateRole Middleware. when i try to print $selectedNavigationId the other navigation link printing that

**Comment by bpocallaghan** [comment]
If you want - you can add me to skype to help you? "bpocallaghan" - my skype name.

The problem is in `TitanAdminController line 217` - can do a `dd($this->selectedNavigation);` - however that file is under the vendor directory - but should find it doing a search filename.

For some reason its not finding the navigation - just would like to see why it does not find it - have a feeling its usually something to do with the navigation_admin table or app url or something else.

If you want to have a read here / for reference 

While waiting for me to respond next [Issue #5](https://github.com/bpocallaghan/laravel-admin-starter/issues/5)

**Comment by truelogicapp** [comment]
Hi @bpocallaghan 

I did same but in my case when I dd ($configuration) then #connection: null

else in other default controller it showing mysql

I am still not able to access model.
