### ISSUE TITLE
reCAPTCHA dependency

### ISSUE THREAD

**Issue by rowan-m** [bpocallaghan/laravel-admin-starter#28]
You have `google/recaptcha` as a dependency. I've recently updated this with a `1.2` release. It *should* be backwards compatible, but obviously you'd want to test that. Happy to respond to issues over at https://github.com/google/recaptcha

**Comment by bpocallaghan** [comment]
Hi @rowan-m 
Thank you, also thanks for giving this package/project a try.
Yes, I do believe it will be without any issues.
Please feel free to contribute if you have any ideas about adding/changing/upgrading.
Happy coding.
