### ISSUE TITLE
Do you have any way to trigger your flash notifications from javascript.

### ISSUE THREAD

**Issue by pakistanihaider** [bpocallaghan/laravel-admin-starter#3]
Nice job. very nice work there.

What i want to ask, do you know of any way of modifying this flash library in a way so that it triggers the notification from js.

**Comment by bpocallaghan** [comment]
Hi @pakistanihaider 

Thank you, If I understand you correctly.

The package's [notify.js](https://github.com/bpocallaghan/notify/blob/master/resources/assets/notify.js#L14)

I also have it in the [navigation order](https://github.com/bpocallaghan/laravel-admin-starter/blob/master/resources/views/admin/partials/nestable.blade.php#L32)

You can then call the notify function.

`notify('Title', 'Message', 'info');`

But perhaps it might be good to give it an update to allow to override the icons / sound as well.
