### ISSUE TITLE
npm run dev - bugs

### ISSUE THREAD

**Issue by d-knafo** [bpocallaghan/laravel-admin-starter#4]
hi 
thanks for your repo !! is great !!

after having done
`npm run dev`
I see these mistakes

![screenshot from 2017-08-21 13-10-35](https://user-images.githubusercontent.com/11031578/29514750-4d397112-8672-11e7-95f6-cc24623dfaa9.png)

**Comment by bpocallaghan** [comment]
Hi @d-knafo 

Thanks.
Mmmm, It seems that it is not finding all the js files `resources\assets\admin\js`.
I know its stupid, but mind checking if you have all the files please. [Link](https://github.com/bpocallaghan/laravel-admin-starter/tree/master/resources/assets/admin/js)

The `admin/js/titan/buttons.js, admin/js/titan/notify.js, etc`

Maybe somewhere the path is different in the `webpack.js` so it does not compile them into your `admin.js`

Please shout if I can be of further assistance...

**Comment by d-knafo** [comment]
thanks

**Comment by d-knafo** [comment]
hi 
I think you forget - this plugin physically,
Can you put them?
thanks.

webpack.mix.js

      ` // plugins
        pathJS + 'vendor/pace.js',
        pathJS + 'vendor/chart.js',
        pathJS + 'vendor/select2.js',
        pathJS + 'vendor/dropzone.js',
        pathJS + 'vendor/lightbox.js',
        pathJS + 'plugins/fastclick.js',
        pathJS + 'vendor/summernote.js',
        pathJS + 'vendor/jquery.nestable.js',
        pathJS + 'vendor/jquery.cookie.js',

        // date picker
        pathJS + 'vendor/moment.js',
        pathJS + 'vendor/daterangepicker.js',
        pathJS + 'vendor/bootstrap-datetimepicker.js',

        // datatables | 1.10.11
        // https://datatables.net/extensions/responsive/classes
        pathJS + 'vendor/jquery.datatables.js',
        pathJS + 'vendor/datatables.bootstrap.js',
        pathJS + 'vendor/datatables.responsive.js',
`

**Comment by bpocallaghan** [comment]
Hi @d-knafo 

[Do you mean these js files](https://github.com/bpocallaghan/laravel-admin-starter/tree/master/resources/assets/admin/js/vendor)

Mind if I ask how you installed it - you can download the 'zip' file  - it should include all these files.

Maybe I am missing something?

**Comment by d-knafo** [comment]
:)
thanks 
and thanks for this project !!!!

**Comment by bpocallaghan** [comment]
No worries.

Glad you like it, Work kept me a bit busy. Will try to add more features (Blog, Image Upload + Crop and some components) - just need to find some time to add them :)

New stuff is definitely coming...

**Comment by d-knafo** [comment]
thanks !!!
