### ISSUE TITLE
Missing migrations

### ISSUE THREAD

**Issue by mariopro** [bpocallaghan/laravel-admin-starter#43]
First, thanks for putting this test project on Github.

It seems like there are migration missing. After following, and completed the installation, when I try to access the admin/blog/categories or admin/blog/articles I get `SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel_as.articles' doesn't exist `

Any other steps that are not described in the documentation?

Thanks

**Comment by bpocallaghan** [comment]
@mariopro 
Thank you for checking out this project and feedback :)
Yes, I actually tried to slim the initial files/tables down by moving some sections 'outside' of the initial install (articles, news, faq, etc) To copy those files over you need to run `php artisan titan:migrate --name=blog` and/or `php artisan titan:migrate --name=news`.

Please look [here](https://github.com/bpocallaghan/titan) for the more in depth documentation/steps about setting it up.  Search for "php artisan titan:migrate --name=" in readme.
Please let me know if its not working.

A side note, I created an updated version (first part TDD oriented) and v3 for adminlte.
If you want to check it out (still in beta - but I will be using it in a new project soon)
[Titan Starter](https://github.com/bpocallaghan/titan-starter)

Have fun!
