### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by johns7890** [bpocallaghan/laravel-admin-starter#7]
(newbs comment incoming)

Olla!. how can I override or display my own views on a newly added page on the admin and/or on the website?

**Comment by bpocallaghan** [comment]
Hi @johns7890 

Lets take the Banners in the admin as an example.
- Create the menu item in admin - settings - navigation - can create new items here.
- Create the controller, model, view files (side note - my generators package [Generators](https://github.com/bpocallaghan/generators))
- Add the resource [routes/web.php](https://github.com/bpocallaghan/laravel-admin-starter/blob/master/routes/web.php#L112)
- In the controller - index method - the view gets returned [BannersController](https://github.com/bpocallaghan/laravel-admin-starter/blob/master/app/Http/Controllers/Admin/General/BannersController.php#L22)
- [banners.index.blade.php](https://github.com/bpocallaghan/laravel-admin-starter/blob/master/resources/views/admin/banners/index.blade.php)

The website have 2 different ways. There is a page builder to dynamically create pages with fixed/set components and then you can create 'custom' pages, for example. Contact Us is custom
Page Builder
- In the Admin - The [Pages Menu](http://bpocallaghan.co.za/admin/pages) You can create pages - Look at the [Content Only](http://bpocallaghan.co.za/pages/content-only), [Content Gallery](http://bpocallaghan.co.za/pages/content-and-gallery), [Content Photo](http://bpocallaghan.co.za/pages/content-and-photo) Examples In the admin you can create these types of pages yourself - without any controllers, views, etc.

Custom Pages
- [Contact Us](http://bpocallaghan.co.za/contact-us)
This works the same as the admin - register the route, create the controller and create the view (blade) file.

Please shout if this helped or not. Was not sure how in detail I must explain it.
I can explain in more detail / answer other questions or send you links of a few good blogs/articles?

Have fun!

**Comment by johns7890** [comment]
wow! that really helps me a lot. awesome!
