### ISSUE TITLE
Not found Profile Page

### ISSUE THREAD

**Issue by cagcak** [bpocallaghan/laravel-admin-starter#9]
After successful registration following error appears when the user directs #to `My Account` :

> Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
> Class 'App\Models\FAQ' not found

Details for the error as follows:

> /home/bpocasgt/app/Http/Controllers/Website/Account/AccountController.php

```
<?php
 
namespace App\Http\Controllers\Website\Account;
 
use App\Models\FAQ;
use App\Http\Requests;
use Illuminate\Http\Request;
use App\Http\Controllers\Website\WebsiteController;
 
class AccountController extends WebsiteController
{
    public function index()
    {
        $faq = FAQ::whereHas('category', function($query) {  // FatalThrowableError :Line 14
            return $query->where('name', 'Account');
        })->orderBy('list_order')->get();
 
        return $this->view('account.account', compact('faq'));
    }
}
```

> Arguments
> "Class 'App\Models\FAQ' not found"

**Comment by bpocallaghan** [comment]
Hi @cagcak 
Thank you for the feedback.
I've recently moved some 'components' to separate packages, seems that I've missed this page.

Thanks for the detailed message and that you might be interested in this package.

I've pushed the fix and uploaded online.

For more information regarding what I've changed - [AccountController](https://github.com/bpocallaghan/laravel-admin-starter/commit/1f490d6866d0c2ecf797dc8d6e89debf6016921e)

**Comment by cagcak** [comment]
Hello @bpocallaghan thanks for the quick support. I saw the change you made.
I must say this; although it is still being developed, the project is an ideal starting point for small-sized startup bussinesses. I've just recommended this project to my junior developer friends.  
Thanks for the project.
